#!/usr/bin/env python3
"""Fusiona entradas nuevas en docs/data/info_fija.json (idempotente)."""
from __future__ import annotations

import json
from pathlib import Path

RAIZ = Path(__file__).resolve().parent.parent
INFO = RAIZ / "docs" / "data" / "info_fija.json"

REF = "2026-06"
REF_NOTE = "TIR aprox. ref. jun 2026; verificar en día hábil."

NUEVOS: dict = {
    # --- Fase 1: Soberanos USD ley argentina ---
    "AL29": {
        "nombre": "Bono AL29",
        "categoria": "Soberano USD",
        "tipo": "Soberano",
        "sector": "Soberanos USD",
        "moneda": "USD",
        "ley": "Argentina",
        "tir_referencia": 8.0,
        "tir_fecha_referencia": REF,
        "vencimiento": "2029-07-09",
        "cupon": "0,75% semestral",
        "cupon_tasa_anual": 0.75,
        "cupon_frecuencia": "semestral",
        "amortizacion": "Bullet",
        "amortizacion_tipo": "bullet",
    },
    "AL35": {
        "nombre": "Bono AL35",
        "categoria": "Soberano USD",
        "tipo": "Soberano",
        "sector": "Soberanos USD",
        "moneda": "USD",
        "ley": "Argentina",
        "tir_referencia": 9.0,
        "tir_fecha_referencia": REF,
        "vencimiento": "2035-07-09",
        "cupon": "0,625% semestral",
        "cupon_tasa_anual": 0.625,
        "cupon_frecuencia": "semestral",
        "amortizacion": "Bullet",
        "amortizacion_tipo": "bullet",
    },
    "AL41": {
        "nombre": "Bono AL41",
        "categoria": "Soberano USD",
        "tipo": "Soberano",
        "sector": "Soberanos USD",
        "moneda": "USD",
        "ley": "Argentina",
        "tir_referencia": 9.5,
        "tir_fecha_referencia": REF,
        "vencimiento": "2041-07-09",
        "cupon": "0,5% semestral",
        "cupon_tasa_anual": 0.5,
        "cupon_frecuencia": "semestral",
        "amortizacion": "Bullet",
        "amortizacion_tipo": "bullet",
    },
    "GD29": {
        "nombre": "Bono GD29",
        "categoria": "Soberano USD",
        "tipo": "Soberano",
        "sector": "Soberanos USD",
        "moneda": "USD",
        "ley": "Nueva York",
        "tir_referencia": 8.0,
        "tir_fecha_referencia": REF,
        "vencimiento": "2029-07-09",
        "cupon": "0,75% semestral",
        "cupon_tasa_anual": 0.75,
        "cupon_frecuencia": "semestral",
        "amortizacion": "Bullet",
        "amortizacion_tipo": "bullet",
    },
    "GD38": {
        "nombre": "Bono GD38",
        "categoria": "Soberano USD",
        "tipo": "Soberano",
        "sector": "Soberanos USD",
        "moneda": "USD",
        "ley": "Nueva York",
        "tir_referencia": 9.5,
        "tir_fecha_referencia": REF,
        "vencimiento": "2038-07-09",
        "cupon": "0,625% semestral",
        "cupon_tasa_anual": 0.625,
        "cupon_frecuencia": "semestral",
        "amortizacion": "Bullet",
        "amortizacion_tipo": "bullet",
    },
    "GD41": {
        "nombre": "Bono GD41",
        "categoria": "Soberano USD",
        "tipo": "Soberano",
        "sector": "Soberanos USD",
        "moneda": "USD",
        "ley": "Nueva York",
        "tir_referencia": 10.0,
        "tir_fecha_referencia": REF,
        "vencimiento": "2041-07-09",
        "cupon": "0,5% semestral",
        "cupon_tasa_anual": 0.5,
        "cupon_frecuencia": "semestral",
        "amortizacion": "Bullet",
        "amortizacion_tipo": "bullet",
    },
    "GD46": {
        "nombre": "Bono GD46",
        "categoria": "Soberano USD",
        "tipo": "Soberano",
        "sector": "Soberanos USD",
        "moneda": "USD",
        "ley": "Nueva York",
        "tir_referencia": 10.5,
        "tir_fecha_referencia": REF,
        "vencimiento": "2046-07-09",
        "cupon": "0,375% semestral",
        "cupon_tasa_anual": 0.375,
        "cupon_frecuencia": "semestral",
        "amortizacion": "Bullet",
        "amortizacion_tipo": "bullet",
    },
    # --- Fase 1: ARS CER (Boncer) ---
    "TX26": {
        "nombre": "Bono TX26 (Boncer)",
        "categoria": "Soberano ARS",
        "tipo": "Soberano",
        "sector": "Soberanos ARS",
        "moneda": "ARS-CER",
        "ley": "Argentina",
        "tir_referencia": 3.5,
        "tir_fecha_referencia": REF,
        "vencimiento": "2026-03-15",
        "cupon": "0% (ajuste CER)",
        "cupon_tasa_anual": 0.0,
        "cupon_frecuencia": "anual",
        "amortizacion": "Bullet",
        "amortizacion_tipo": "bullet",
        "notas": "TIR ref. en pesos reales (CER); no comparable con USD.",
    },
    "TX28": {
        "nombre": "Bono TX28 (Boncer)",
        "categoria": "Soberano ARS",
        "tipo": "Soberano",
        "sector": "Soberanos ARS",
        "moneda": "ARS-CER",
        "ley": "Argentina",
        "tir_referencia": 4.0,
        "tir_fecha_referencia": REF,
        "vencimiento": "2028-06-15",
        "cupon": "2% anual + CER",
        "cupon_tasa_anual": 2.0,
        "cupon_frecuencia": "anual",
        "amortizacion": "Bullet",
        "amortizacion_tipo": "bullet",
    },
    "TZX26": {
        "nombre": "Bono TZX26 (Boncer cupón cero)",
        "categoria": "Soberano ARS",
        "tipo": "Soberano",
        "sector": "Soberanos ARS",
        "moneda": "ARS-CER",
        "ley": "Argentina",
        "tir_referencia": 3.0,
        "tir_fecha_referencia": REF,
        "vencimiento": "2026-06-30",
        "cupon": "0% (ajuste CER)",
        "cupon_tasa_anual": 0.0,
        "cupon_frecuencia": "anual",
        "amortizacion": "Bullet",
        "amortizacion_tipo": "bullet",
    },
    "TZXD6": {
        "nombre": "Bono TZXD6 (Boncer)",
        "categoria": "Soberano ARS",
        "tipo": "Soberano",
        "sector": "Soberanos ARS",
        "moneda": "ARS-CER",
        "ley": "Argentina",
        "tir_referencia": 2.5,
        "tir_fecha_referencia": REF,
        "vencimiento": "2026-12-15",
        "cupon": "0% (ajuste CER)",
        "cupon_tasa_anual": 0.0,
        "cupon_frecuencia": "anual",
        "amortizacion": "Bullet",
        "amortizacion_tipo": "bullet",
    },
    # --- Fase 1: Lecaps ARS (verificación tickers jun 2026) ---
    "S31L6": {
        "nombre": "Lecap S31L6 (jul 2026)",
        "categoria": "Soberano ARS",
        "tipo": "Soberano",
        "sector": "Soberanos ARS",
        "moneda": "ARS",
        "ley": "Argentina",
        "tir_referencia": 13.0,
        "tir_fecha_referencia": REF,
        "vencimiento": "2026-07-31",
        "cupon": "Capitalizable mensual (~33% TNA ref.)",
        "cupon_tasa_anual": 33.0,
        "cupon_frecuencia": "mensual",
        "amortizacion": "Bullet al vencimiento",
        "amortizacion_tipo": "bullet",
        "notas": "Lecap de tasa fija capitalizable; TIR mercado aprox. limitada en el panel.",
    },
    "S31G6": {
        "nombre": "Lecap S31G6 (ago 2026)",
        "categoria": "Soberano ARS",
        "tipo": "Soberano",
        "sector": "Soberanos ARS",
        "moneda": "ARS",
        "ley": "Argentina",
        "tir_referencia": 25.0,
        "tir_fecha_referencia": REF,
        "vencimiento": "2026-08-31",
        "cupon": "Capitalizable mensual",
        "cupon_tasa_anual": 24.88,
        "cupon_frecuencia": "mensual",
        "amortizacion": "Bullet",
        "amortizacion_tipo": "bullet",
    },
    "S30O6": {
        "nombre": "Lecap S30O6 (oct 2026)",
        "categoria": "Soberano ARS",
        "tipo": "Soberano",
        "sector": "Soberanos ARS",
        "moneda": "ARS",
        "ley": "Argentina",
        "tir_referencia": 22.0,
        "tir_fecha_referencia": REF,
        "vencimiento": "2026-10-30",
        "cupon": "Capitalizable mensual",
        "cupon_tasa_anual": 22.0,
        "cupon_frecuencia": "mensual",
        "amortizacion": "Bullet",
        "amortizacion_tipo": "bullet",
    },
    "S30N6": {
        "nombre": "Lecap S30N6 (nov 2026)",
        "categoria": "Soberano ARS",
        "tipo": "Soberano",
        "sector": "Soberanos ARS",
        "moneda": "ARS",
        "ley": "Argentina",
        "tir_referencia": 18.0,
        "tir_fecha_referencia": REF,
        "vencimiento": "2026-11-30",
        "cupon": "Capitalizable mensual",
        "cupon_tasa_anual": 18.0,
        "cupon_frecuencia": "mensual",
        "amortizacion": "Bullet",
        "amortizacion_tipo": "bullet",
    },
    "S17L6": {
        "nombre": "Lecap S17L6 (jul 2026 corta)",
        "categoria": "Soberano ARS",
        "tipo": "Soberano",
        "sector": "Soberanos ARS",
        "moneda": "ARS",
        "ley": "Argentina",
        "tir_referencia": 15.0,
        "tir_fecha_referencia": REF,
        "vencimiento": "2026-07-17",
        "cupon": "Capitalizable mensual",
        "cupon_tasa_anual": 15.0,
        "cupon_frecuencia": "mensual",
        "amortizacion": "Bullet",
        "amortizacion_tipo": "bullet",
    },
    "T30J6": {
        "nombre": "Letra / bono corto T30J6",
        "categoria": "Soberano ARS",
        "tipo": "Soberano",
        "sector": "Soberanos ARS",
        "moneda": "ARS",
        "ley": "Argentina",
        "tir_referencia": 20.0,
        "tir_fecha_referencia": REF,
        "vencimiento": "2026-06-30",
        "cupon": "Tasa fija",
        "cupon_tasa_anual": 20.0,
        "cupon_frecuencia": "mensual",
        "amortizacion": "Bullet",
        "amortizacion_tipo": "bullet",
    },
    # --- Fase 1: ARS dollar-linked ---
    "TVPP": {
        "nombre": "Bono TVPP (dollar-linked)",
        "categoria": "Soberano ARS",
        "tipo": "Soberano",
        "sector": "Soberanos ARS",
        "moneda": "ARS dollar-linked",
        "ley": "Argentina",
        "tir_referencia": 5.0,
        "tir_fecha_referencia": REF,
        "vencimiento": "2028-07-09",
        "cupon": "Cupón en pesos indexado USD",
        "cupon_tasa_anual": 1.0,
        "cupon_frecuencia": "semestral",
        "amortizacion": "Bullet",
        "amortizacion_tipo": "bullet",
        "notas": "Precio en pesos ligado al tipo de cambio; TIR ref. no comparable con USD hard.",
    },
    "DICP": {
        "nombre": "Bono DICP (dollar-linked)",
        "categoria": "Soberano ARS",
        "tipo": "Soberano",
        "sector": "Soberanos ARS",
        "moneda": "ARS dollar-linked",
        "ley": "Argentina",
        "tir_referencia": 4.5,
        "tir_fecha_referencia": REF,
        "vencimiento": "2029-01-15",
        "cupon": "Cupón en pesos indexado USD",
        "cupon_tasa_anual": 1.0,
        "cupon_frecuencia": "semestral",
        "amortizacion": "Bullet",
        "amortizacion_tipo": "bullet",
    },
    # --- Fase 2: Provinciales USD Tier 1 ---
    "CO26D": {
        "nombre": "Bono Córdoba 2026 USD",
        "categoria": "Provincial",
        "tipo": "Provincial",
        "sector": "Provincial Córdoba",
        "moneda": "USD",
        "ley": "Nueva York / exterior",
        "tir_referencia": 12.0,
        "tir_fecha_referencia": REF,
        "vencimiento": "2026-04-29",
        "cupon": "6,5% semestral",
        "cupon_tasa_anual": 6.5,
        "cupon_frecuencia": "semestral",
        "amortizacion": "Bullet",
        "amortizacion_tipo": "bullet",
    },
    "CO27D": {
        "nombre": "Bono Córdoba 2027 USD",
        "categoria": "Provincial",
        "tipo": "Provincial",
        "sector": "Provincial Córdoba",
        "moneda": "USD",
        "ley": "Nueva York / exterior",
        "tir_referencia": 11.0,
        "tir_fecha_referencia": REF,
        "vencimiento": "2027-04-30",
        "cupon": "Semestral",
        "cupon_tasa_anual": 6.0,
        "cupon_frecuencia": "semestral",
        "amortizacion": "Bullet",
        "amortizacion_tipo": "bullet",
    },
    "PM29D": {
        "nombre": "Bono Mendoza 2029 USD",
        "categoria": "Provincial",
        "tipo": "Provincial",
        "sector": "Provincial Mendoza",
        "moneda": "USD",
        "ley": "Nueva York / exterior",
        "tir_referencia": 18.0,
        "tir_fecha_referencia": REF,
        "vencimiento": "2029-03-15",
        "cupon": "Semestral",
        "cupon_tasa_anual": 7.0,
        "cupon_frecuencia": "semestral",
        "amortizacion": "Bullet",
        "amortizacion_tipo": "bullet",
    },
    "SA24D": {
        "nombre": "Bono Salta 2027 USD (reestructurado)",
        "categoria": "Provincial",
        "tipo": "Provincial",
        "sector": "Provincial Salta",
        "moneda": "USD",
        "ley": "Nueva York / exterior",
        "tir_referencia": 20.0,
        "tir_fecha_referencia": REF,
        "vencimiento": "2027-12-15",
        "cupon": "Step-up USD",
        "cupon_tasa_anual": 8.0,
        "cupon_frecuencia": "semestral",
        "amortizacion": "Bullet",
        "amortizacion_tipo": "bullet",
    },
    "NDT5D": {
        "nombre": "Bono Neuquén 2030 USD",
        "categoria": "Provincial",
        "tipo": "Provincial",
        "sector": "Provincial Neuquén",
        "moneda": "USD",
        "ley": "Nueva York / exterior",
        "tir_referencia": 16.0,
        "tir_fecha_referencia": REF,
        "vencimiento": "2030-04-30",
        "cupon": "Semestral",
        "cupon_tasa_anual": 7.5,
        "cupon_frecuencia": "semestral",
        "amortizacion": "Bullet",
        "amortizacion_tipo": "bullet",
    },
    "BA37D": {
        "nombre": "Bono Pcia. Buenos Aires 2037 USD",
        "categoria": "Provincial",
        "tipo": "Provincial",
        "sector": "Provincial Buenos Aires",
        "moneda": "USD",
        "ley": "Nueva York / exterior",
        "tir_referencia": 22.0,
        "tir_fecha_referencia": REF,
        "vencimiento": "2037-10-15",
        "cupon": "Semestral",
        "cupon_tasa_anual": 6.0,
        "cupon_frecuencia": "semestral",
        "amortizacion": "Bullet",
        "amortizacion_tipo": "bullet",
    },
    "BACAD": {
        "nombre": "Bono Ciudad de Buenos Aires (BACAD)",
        "categoria": "Provincial",
        "tipo": "Provincial",
        "sector": "Ciudad de Buenos Aires",
        "moneda": "USD",
        "ley": "Exterior",
        "tir_referencia": 15.0,
        "tir_fecha_referencia": REF,
        "vencimiento": "2027-12-31",
        "cupon": "Semestral",
        "cupon_tasa_anual": 6.0,
        "cupon_frecuencia": "semestral",
        "amortizacion": "Bullet",
        "amortizacion_tipo": "bullet",
        "notas": "Clasificado como sub-soberano CABA; verificar prospecto en día hábil.",
    },
    "BACAO": {
        "nombre": "Bono Ciudad de Buenos Aires (BACAO)",
        "categoria": "Provincial",
        "tipo": "Provincial",
        "sector": "Ciudad de Buenos Aires",
        "moneda": "USD",
        "ley": "Exterior",
        "tir_referencia": 16.0,
        "tir_fecha_referencia": REF,
        "vencimiento": "2028-12-31",
        "cupon": "Semestral",
        "cupon_tasa_anual": 6.5,
        "cupon_frecuencia": "semestral",
        "amortizacion": "Bullet",
        "amortizacion_tipo": "bullet",
    },
    # --- Fase 4: BCRA ---
    "BPO27": {
        "nombre": "BOPREAL Serie 1 (BPO27)",
        "categoria": "BCRA",
        "tipo": "BCRA",
        "sector": "BCRA",
        "moneda": "USD",
        "ley": "Argentina (BCRA)",
        "tir_referencia": 0.0,
        "tir_fecha_referencia": REF,
        "vencimiento": "2027-03-15",
        "cupon": "0% (certificado)",
        "cupon_tasa_anual": 0.0,
        "cupon_frecuencia": "anual",
        "amortizacion": "Bullet",
        "amortizacion_tipo": "bullet",
        "notas": "BOPREAL: instrumento BCRA, no bono soberano tradicional.",
    },
    "BPO28": {
        "nombre": "BOPREAL Serie 2 (BPO28)",
        "categoria": "BCRA",
        "tipo": "BCRA",
        "sector": "BCRA",
        "moneda": "USD",
        "ley": "Argentina (BCRA)",
        "tir_referencia": 0.0,
        "tir_fecha_referencia": REF,
        "vencimiento": "2028-03-15",
        "cupon": "0%",
        "cupon_tasa_anual": 0.0,
        "cupon_frecuencia": "anual",
        "amortizacion": "Bullet",
        "amortizacion_tipo": "bullet",
    },
    "BPOD7": {
        "nombre": "BOPREAL (BPOD7)",
        "categoria": "BCRA",
        "tipo": "BCRA",
        "sector": "BCRA",
        "moneda": "USD",
        "ley": "Argentina (BCRA)",
        "tir_referencia": 0.0,
        "tir_fecha_referencia": REF,
        "vencimiento": "2027-12-31",
        "cupon": "0%",
        "cupon_tasa_anual": 0.0,
        "cupon_frecuencia": "anual",
        "amortizacion": "Bullet",
        "amortizacion_tipo": "bullet",
    },
    # --- Fase 4: CEDEAR ETF renta fija (proxy) ---
    "SPYD": {
        "nombre": "CEDEAR SPYD (ETF S&P Dividend)",
        "categoria": "CEDEAR",
        "tipo": "CEDEAR",
        "sector": "CEDEAR",
        "moneda": "USD",
        "ley": "EE.UU. (subyacente)",
        "tir_referencia": 3.5,
        "tir_fecha_referencia": REF,
        "vencimiento": "Perpetuo (ETF)",
        "cupon": "Dividendos distribuidos",
        "cupon_tasa_anual": 3.5,
        "cupon_frecuencia": "trimestral",
        "amortizacion": "N/A (equity ETF)",
        "amortizacion_tipo": "bullet",
        "notas": "CEDEAR de ETF estadounidense; NO es bono argentino. TIR ref. ilustrativa.",
    },
}


def main() -> None:
    data = json.loads(INFO.read_text(encoding="utf-8"))
    # Actualizar sector/categoria de soberanos existentes
    for t in ("AL30", "GD30", "GD35"):
        if t in data:
            data[t]["sector"] = "Soberanos USD"
            data[t]["categoria"] = "Soberano USD"
    merged = 0
    for ticker, entry in NUEVOS.items():
        if ticker not in data:
            data[ticker] = entry
            merged += 1
        else:
            data[ticker].update(entry)
    data["_comentario"] = (
        "Valores de referencia aproximados (abr–jun 2026). Campo categoria para filtros del panel. "
        + REF_NOTE
    )
    INFO.write_text(json.dumps(data, indent=2, ensure_ascii=False) + "\n", encoding="utf-8")
    print(f"info_fija: {merged} entradas nuevas, total {sum(1 for k in data if not k.startswith('_'))}")


if __name__ == "__main__":
    main()
